fix(Bechamel_perf): avoid permission error when not running as root
`Bechamel_perf` fails to load, even if we haven't tried to measure any
event yet:
```
utop# Printexc.record_backtrace true;;
utop# #require "bechamel-perf";;
Exception: Failure "Permission denied".
Raised by primitive operation at Mperf.make in file "mperf/lib/mperf.ml", lines 190-191, characters 8-16
Called from Bechamel__Measure.instance in file "lib/measure.ml", line 19, characters 8-19
Called from Bechamel_perf.Instance.cycles in file "lib/perf/bechamel_perf.ml", line 154, characters 15-64
Called from Topeval.load_compunit in file "toplevel/byte/topeval.ml",
line 239, characters 11-23
```

Workarounds:

* `sudo sysctl -w kernel.perf_event_paranoid=1`
* run as root

However `perf` can be used by non-root users if we exclude measuring the
kernel, so catch the `EACCES` error and exclude the kernel.
This is similar to how `perf stat` itself works.

There is no change when run as root, or when the paranoid setting is
less strict: we can measure both userspace and kernel in that case.

Signed-off-by: Edwin Török <edwin.torok@cloud.com>